defaults: &defaults
  docker:
    - image: iopipe/circleci
  working_directory: ~/circleci-deployment

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn test
      # test also runs the build, so save the dist for later
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  acceptanceTests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run acceptance

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run build
      - run: cp .npmrc-ci .npmrc
      - run: yarn run release

workflows:
  version: 2
  all:
    jobs:
      - install
      - test:
          requires:
            - install
      - acceptanceTests:
          requires:
            - install
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - install
            - test
            - acceptanceTests
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
